#!/bin/bash -l
#PBS -l nodes=1:ppn=1
#PBS -l walltime=20:30:00
#PBS -l mem=32gb
#PBS -m bea
#PBS M wenjia.wang0315@gmail.com
module purge
ml load matplotlib/2.1.0-foss-2017b-Python-3.6.3
ml load scikit-learn/0.19.1-foss-2017b-Python-3.6.3
cd $HOME
cd explore-m-bandits-master
m=10
bandit="linear"
min_L=0.0
min_U=0.9
sum_L=0.0
sum_U=8.5
Success_L=0.0
Success_U=1.0
python3 plot_topm.py -a 1000 -st 150000 -m ${m} -b ${bandit} -n 200 -R_0 1.4 -min_L ${min_L} -min_U ${min_U} -sum_L ${sum_L}
